# based on https://raw.githubusercontent.com/EOSIO/eos/master/Docker/docker-compose-dawn3.0.yaml
version: "3"

services:
  nodeosd:
    image: eosio/eos-dev
    command: nodeos -e -p eosio --plugin eosio::wallet_api_plugin --plugin eosio::wallet_plugin --plugin eosio::producer_plugin --plugin eosio::history_plugin --plugin eosio::chain_api_plugin --plugin eosio::history_api_plugin --plugin eosio::http_plugin -d /mnt/dev/data --config-dir /mnt/dev/config --http-server-address=0.0.0.0:8888 --access-control-allow-origin=* --contracts-console
    hostname: nodeosd
    ports:
      - 8888:8888
      - 9876:9876
    expose:
      - "8888"
    volumes:
      - /tmp/work:/work
      - /tmp/eosio/data:/mnt/dev/data
      - /tmp/eosio/config:/mnt/dev/config
      - ${PWD}/config/config.ini:/mnt/dev/config/config.ini
    cap_add:
      - IPC_LOCK
    stop_grace_period: 10m

  keosd:
    image: eosio/eos-dev
    command: /opt/eosio/bin/keosd --wallet-dir /opt/eosio/data-dir --http-server-address=127.0.0.1:8900 --http-alias=keosd:8900 --http-alias=localhost:8900
    hostname: keosd
    links:
      - nodeosd:nodeos
    volumes:
      - /tmp/eosio/keosd:/opt/eosio/data-dir
      - ${PWD}/Project:/work
      - ${PWD}/keys:/keys
      - ${PWD}/config/bashrc:/bashrc
    stop_grace_period: 10m

# services:
  # eosio:
  #   hostname: eosio
  #   container_name: eosio
  #   image: eosio/eos-dev
  #   command: nodeos -e -p eosio --plugin eosio::wallet_api_plugin --plugin eosio::wallet_plugin --plugin eosio::producer_plugin --plugin eosio::history_plugin --plugin eosio::chain_api_plugin --plugin eosio::history_api_plugin --plugin eosio::http_plugin -d /mnt/dev/data --config-dir /mnt/dev/config --http-server-address=0.0.0.0:8888 --access-control-allow-origin=* --contracts-console
  #   ports:
  #     - "8888:8888"
  #     - "9876:9876"
  #   expose:
  #     - "8888"
  #   volumes:
  #     - /tmp/work:/work
  #     - /tmp/eosio/data:/mnt/dev/data
  #     - /tmp/eosio/config:/mnt/dev/config
  #     - ${PWD}/config.ini:/mnt/dev/config/config.ini
